export const mockUser = {
  created: 1619760527,
  deleted: 0,
  email: "Test123@gmail.com",
  id: 572287,
  login_attempts: 0,
  login_attempts_last: null,
  modified: 1627276598,
  properties: {
    PN_First_Page_Visited: "https%3A%2F%2Fwww.pubnub.com%2F",
    PN_Page_Before_Sign_Up: "https%253A%252F%252Fdashboard.pubnub.com%252Flogin",
    first: "Test",
    last: "123",
    lead_conversion_cta: "",
    lead_conversion_page: "",
    newsletter_opt_in: 1,
    phone: 8699350737,
    utm_ad_group: "",
    utm_campaign: "",
    utm_content: "",
    utm_creative: "",
    utm_device: "",
    utm_key_word: "",
    utm_matchtype: "",
    utm_medium: "",
    utm_network: "",
    utm_placement: "",
    utm_source: "",
    utm_target: "",
    utm_term: "",
    utm_website_url: "https%3A%2F%2Fwww.pubnub.com%2Fdocs%2Fchat%2Fcomponents%2Foverview",
    website: "https://dummyurl.com/",
  },
  status: 4,
  transaction_pricing_plan: null,
  verified_expires: null,
};

export default null;
